from .system_prompts import SIMPLE_PROMPT, CODE_PROMPT
from .few_shots import MATH_FEW_SHOT, DOUBLECHECK_FEW_SHOT, CODE_FEW_SHOT

__all__ = ["SIMPLE_PROMPT", "MATH_FEW_SHOT", "DOUBLECHECK_FEW_SHOT", "CODE_FEW_SHOT", "CODE_PROMPT"]